### ISSUE TITLE
Win 10 - R and Java 64 bit - Error when installing iSAX

### ISSUE THREAD

**Issue by kamakay** [blogsvoices/iSAX#1]
Dear ISAX Team,

I am working with R 3.4.1 64bit on RStudio using java jdk 1.8.22 64bit on Windows 10.

When installing ISAX with the command **install_github("blogsvoices/iSAX")** I obtain this Error:

> * installing *source* package 'iSAX' ...
> ** R
> ** data
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> Error: package or namespace load failed for 'rJava':
>  .onLoad failed in loadNamespace() for 'rJava', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: unable to load shared object 'C:/Users/robbyg/R/win-library/3.4/rJava/libs/i386/rJava.dll':
>   LoadLibrary failure:  %1 is not a valid Win32 application.
> 
> Error : package 'rJava' could not be loaded
> Error: loading failed
> Execution halted
> *** arch - x64
> ERROR: loading failed for 'i386'
> * removing 'C:/Users/robbyg/R/win-library/3.4/iSAX'
> Installation failed: Command failed (1)

Can you help me to figure out how to solve this issue?

Thanks
Roberto

**Comment by siacus** [comment]
hi Roberto,
you need to install rJava. Apparently you have Java 32bit in your path

library/3.4/rJava/libs/i386/rJava.dll':
LoadLibrary failure: %1 is not a valid Win32 application.


but you are using R/R Studio 64bit. This is a Windows specific problem which I don't know how to fix, but you can look at the "R for Windows FAQ" on CRAN.
